I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 710, in script
    Boss "Who are you?"
Exception: Sayer 'Boss' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 710, in script
    Boss "Who are you?"
  File "/home/leopoldguyot/.local/manually_installed/renpy-8.0.3-sdk/renpy/ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/leopoldguyot/.local/manually_installed/renpy-8.0.3-sdk/renpy/ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Boss' is not defined.

Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.0.3.22090809
The amino acid journey 0.1
Thu Mar 30 17:25:59 2023
